# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PasswordForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 316)
        Form.setMinimumSize(QtCore.QSize(250, 150))
        Form.setMaximumSize(QtCore.QSize(1000, 600))
        self.labeluser = QtWidgets.QLabel(Form)
        self.labeluser.setGeometry(QtCore.QRect(60, 60, 111, 31))
        self.labeluser.setObjectName("labeluser")
        self.labelpassword = QtWidgets.QLabel(Form)
        self.labelpassword.setGeometry(QtCore.QRect(60, 100, 111, 31))
        self.labelpassword.setObjectName("labelpassword")
        self.inputuser = QtWidgets.QLineEdit(Form)
        self.inputuser.setGeometry(QtCore.QRect(180, 60, 200, 30))
        self.inputuser.setObjectName("inputuser")
        self.inputpassword = QtWidgets.QLineEdit(Form)
        self.inputpassword.setGeometry(QtCore.QRect(180, 100, 200, 30))
        self.inputpassword.setObjectName("inputpassword")
        self.labelor = QtWidgets.QLabel(Form)
        self.labelor.setGeometry(QtCore.QRect(30, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelor.setFont(font)
        self.labelor.setObjectName("labelor")
        self.labelcookie = QtWidgets.QLabel(Form)
        self.labelcookie.setGeometry(QtCore.QRect(60, 220, 111, 31))
        self.labelcookie.setObjectName("labelcookie")
        self.labelUA = QtWidgets.QLabel(Form)
        self.labelUA.setGeometry(QtCore.QRect(60, 180, 111, 31))
        self.labelUA.setObjectName("labelUA")
        self.inputUA = QtWidgets.QLineEdit(Form)
        self.inputUA.setGeometry(QtCore.QRect(180, 180, 200, 30))
        self.inputUA.setObjectName("inputUA")
        self.inputcookie = QtWidgets.QLineEdit(Form)
        self.inputcookie.setGeometry(QtCore.QRect(180, 220, 200, 30))
        self.inputcookie.setObjectName("inputcookie")
        self.labelcontent = QtWidgets.QLabel(Form)
        self.labelcontent.setGeometry(QtCore.QRect(30, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelcontent.setFont(font)
        self.labelcontent.setObjectName("labelcontent")
        self.buttonconfirm_user = QtWidgets.QPushButton(Form)
        self.buttonconfirm_user.setGeometry(QtCore.QRect(130, 270, 71, 31))
        self.buttonconfirm_user.setObjectName("buttonconfirm_user")
        self.buttoncancel_user = QtWidgets.QPushButton(Form)
        self.buttoncancel_user.setGeometry(QtCore.QRect(330, 270, 71, 31))
        self.buttoncancel_user.setObjectName("buttoncancel_user")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登入資訊"))
        self.labeluser.setText(_translate("Form", "帳號 username:"))
        self.labelpassword.setText(_translate("Form", "密碼 password:"))
        self.labelor.setText(_translate("Form", "或是"))
        self.labelcookie.setText(_translate("Form", "Cookie:"))
        self.labelUA.setText(_translate("Form", "User-Agent:"))
        self.labelcontent.setText(_translate("Form", "content"))
        self.buttonconfirm_user.setText(_translate("Form", "確認"))
        self.buttoncancel_user.setText(_translate("Form", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
