# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 235);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboChoose = QtWidgets.QComboBox(self.centralwidget)
        self.comboChoose.setGeometry(QtCore.QRect(160, 20, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboChoose.setFont(font)
        self.comboChoose.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(171, 171, 171);\n"
"")
        self.comboChoose.setObjectName("comboChoose")
        self.comboChoose.addItem("")
        self.comboChoose.addItem("")
        self.labelChoose = QtWidgets.QLabel(self.centralwidget)
        self.labelChoose.setGeometry(QtCore.QRect(40, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelChoose.setFont(font)
        self.labelChoose.setObjectName("labelChoose")
        self.labelURL = QtWidgets.QLabel(self.centralwidget)
        self.labelURL.setGeometry(QtCore.QRect(40, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelURL.setFont(font)
        self.labelURL.setObjectName("labelURL")
        self.buttonChooseConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.buttonChooseConfirm.setGeometry(QtCore.QRect(470, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonChooseConfirm.setFont(font)
        self.buttonChooseConfirm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonChooseConfirm.setObjectName("buttonChooseConfirm")
        self.inputURL = QtWidgets.QLineEdit(self.centralwidget)
        self.inputURL.setGeometry(QtCore.QRect(160, 90, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputURL.setFont(font)
        self.inputURL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputURL.setObjectName("inputURL")
        self.textProcess = QtWidgets.QTextBrowser(self.centralwidget)
        self.textProcess.setGeometry(QtCore.QRect(40, 200, 471, 261))
        self.textProcess.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textProcess.setObjectName("textProcess")
        self.buttonURLConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.buttonURLConfirm.setGeometry(QtCore.QRect(470, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonURLConfirm.setFont(font)
        self.buttonURLConfirm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonURLConfirm.setObjectName("buttonURLConfirm")
        self.labelCrawler = QtWidgets.QLabel(self.centralwidget)
        self.labelCrawler.setGeometry(QtCore.QRect(160, 150, 481, 31))
        self.labelCrawler.setText("")
        self.labelCrawler.setObjectName("labelCrawler")
        self.buttonReset = QtWidgets.QPushButton(self.centralwidget)
        self.buttonReset.setGeometry(QtCore.QRect(359, 480, 151, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonReset.setFont(font)
        self.buttonReset.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonReset.setObjectName("buttonReset")
        self.buttonRename = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRename.setGeometry(QtCore.QRect(110, 480, 151, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRename.setFont(font)
        self.buttonRename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonRename.setObjectName("buttonRename")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "alice爬蟲系統"))
        self.comboChoose.setItemText(0, _translate("MainWindow", "eyny圖片爬取"))
        self.comboChoose.setItemText(1, _translate("MainWindow", "test用的沒作用"))
        self.labelChoose.setText(_translate("MainWindow", "選擇項目:"))
        self.labelURL.setText(_translate("MainWindow", "輸入網址:"))
        self.buttonChooseConfirm.setText(_translate("MainWindow", "確認"))
        self.buttonURLConfirm.setText(_translate("MainWindow", "確認"))
        self.buttonReset.setText(_translate("MainWindow", "清空資料"))
        self.buttonRename.setText(_translate("MainWindow", "重新命名檔案"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
